service: ${env:GITHUB_REPO_NAME}

custom:
  PROJECT: Twitter DEFI trend functions

provider: ${file(./serverless-provider.yml)}

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

package:
  patterns:
    - '!*'
    - '!*/**'
    - 'dist/*'
    - 'dist/*/**'

stepFunctions:
  stateMachines:
    iteratble_writer_saveTopEntitiesByAll:
      events:
        - schedule: rate(1 minute) # examples: rate(1 minute), rate(60 minutes)
      definition:
        StartAt: Iterator
        States:
          Iterator:
            Type: Task
            Resource:
              Fn::GetAtt: [writer_saveTopEntitiesByAll, Arn]
            ResultPath: "$.taskresult"
            Next: IsCountReached
          IsCountReached:
            Type: Choice
            Choices:
              - Variable: "$.taskresult.continue"
                BooleanEquals: true
                Next: Wait
            Default: Done
          Wait:
            Type: Wait
            Seconds: 3
            Next: Iterator
          Done:
            Type: Pass
            End: true
    iteratble_writer_saveTopEntitiesByList:
      events:
        - schedule:
            rate: rate(1 minute) # examples: rate(1 minute), rate(60 minutes)
            enabled: true
            input:
              pathParameters:
                listId: "1413118800363458560"
      definition:
        StartAt: Iterator
        States:
          Iterator:
            Type: Task
            Resource:
              Fn::GetAtt: [writer_saveTopEntitiesByList, Arn]
            ResultPath: "$.taskresult"
            Next: IsCountReached
          IsCountReached:
            Type: Choice
            Choices:
              - Variable: "$.taskresult.continue"
                BooleanEquals: true
                Next: Wait
            Default: Done
          Wait:
            Type: Wait
            Seconds: 10
            Next: Iterator
          Done:
            Type: Pass
            End: true

functions:
  writer_saveTopEntitiesByAll:
    handler: dist/index.writer_saveTopEntitiesByAll
    fileSystemConfig: ${file(./serverless-fs.yml)}
  writer_saveTopEntitiesByList:
    handler: dist/index.writer_saveTopEntitiesByList
    fileSystemConfig: ${file(./serverless-fs.yml)}
  writer_cleanAndSavePeriodTopEntities:
    handler: dist/index.writer_cleanAndSavePeriodTopEntities
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - schedule: cron(59 23 * * ? *)
  writer_cleanAndSavePeriodTopEnOfList:
    handler: dist/index.writer_cleanAndSavePeriodTopEntitiesOfList
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - schedule:
          rate: cron(12 8 * * ? *)
          enabled: true
          pathParameters:
            listId: "1413118800363458560"
  reader_fetchTopEntities:
    handler: dist/index.reader_fetchTopEntities
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: fetchTopEntities
          method: get
          cors: true
  reader_fetchTopEntitiesOfList:
    handler: dist/index.reader_fetchTopEntitiesOfList
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: fetchTopEntitiesOfList/{listId}
          method: get
          cors: true
  reader_fetchActiveUsersOfList:
    handler: dist/index.reader_fetchActiveUsersOfList
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: fetchActiveUsersOfList/{listId}
          method: get
          cors: true
  reader_fetchPeriodTopEntities:
    handler: dist/index.reader_fetchPeriodTopEntities
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: fetchPeriodTopEntities
          method: get
          cors: true
  reader_fetchPeriodTopEntitiesOfList:
    handler: dist/index.reader_fetchPeriodTopEntitiesOfList
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: fetchPeriodTopEntitiesOfList/{listId}
          method: get
          cors: true
  reader_fetchTweetsByTag:
    handler: dist/index.reader_fetchTweetsByTag
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: fetchTweetsByTag/{filter}/{sinceId}
          method: get
          cors: true
      - http:
          path: fetchTweetsByTag/{filter}
          method: get
          cors: true
  writer_cleanDB:
    handler: dist/index.writer_cleanDB
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: cleanDB/{param}/{secret}/{listId}
          method: get
          cors: true
      - http:
          path: cleanDB/{param}/{secret}
          method: get
          cors: true
