service: ${env:GITHUB_REPO_NAME}

custom:
  PROJECT: Example Squad by Zlotin # change this to your squad name

provider: ${file(./serverless-provider.yml)}

package:
  patterns:
    - '!*'
    - '!*/**'
    - 'dist/*'
    - 'dist/*/**'

functions:
  writer:
    handler: dist/index.writer
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - schedule: rate(1 minute) # examples: rate(1 minute), rate(60 minutes)
  reader:
    handler: dist/index.reader
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: read/{param}
          method: get
          cors: true
