service: ${env:GITHUB_REPO_NAME}

custom:
  PROJECT: Twitter DEFI trend functions

provider: ${file(./serverless-provider.yml)}

package:
  patterns:
    - '!*'
    - '!*/**'
    - 'dist/*'
    - 'dist/*/**'

functions:
  writer_saveTopEntities:
    handler: dist/index.writer_saveTopEntities
    timeout: 60
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - schedule: rate(1 minute) # examples: rate(1 minute), rate(60 minutes)
  writer_cleanAndSavePeriodTopEntities:
    handler: dist/index.writer_cleanAndSavePeriodTopEntities
    timeout: 12
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - schedule: cron(0 0 * * ? *) # examples: rate(1 minute), rate(60 minutes), cron(0 12 * * ? *)
  reader_fetchTopEntities:
    handler: dist/index.reader_fetchTopEntities
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: fetchTopEntities
          method: get
          cors: true
  reader_fetchPeriodTopEntities:
    handler: dist/index.reader_fetchPeriodTopEntities
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: fetchPeriodTopEntities
          method: get
          cors: true
